### PR TITLE
add mattermost link

### LINKED ISSUE #53: Add Mattermost to community links
Currently it only lists:
* Telegram
* Twitter
* GitHub
* IRC

Shown at least in two places https://cutter.re/#community and the footer.

### PR DESCRIPTION
**Pull request by r3yc0n1c**
closes #53 

Fontawesome does not have **fa-mattermost** it seems ( [ref](https://github.com/FortAwesome/Font-Awesome/issues/9727) ) ... I've added the icons as svg instead.

### Screenshots
Community Section
image

Footer Section
image

### CODE REVIEW

**Comment by karliss** [comment]
Maybe the order should be updated as well.  I would say Mattermost, IRC, Telegram, considering that Mattermost is currently the preferred platform.

IRC has it's purpose for those who don't want to create an account or prefer using client of their choice.  If I am not mistaken, Telegram is  there mostly because it was previous preferred platform. It's nice to have for those who already use Telegram for other communication, but bridging has it's limitations. 

What do others think?

**Comment by XVilka** [comment]
ALso, I suppose we should change Twitter to X now. Maybe write something like that "X (formerly Twitter)"

**Comment by XVilka** [comment]
One more thing - we don't have a separate Cutter account, but there is a Rizin one in Mastodon: https://fosstodon.org/@rizin

**Comment by wargio** [comment]
> ALso, I suppose we should change Twitter to X now. Maybe write something like that "X (formerly Twitter)"

Just do X/Twitter

**Comment by r3yc0n1c** [comment]
:raised_hands: updated!

image
image

**Comment by r3yc0n1c** [comment]
:raised_hands: updated!

image
image

**Review by Rot127 — APPROVED** [review]

**Review by karliss — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Pull request merged**
